### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mbtamuli** [deepskandpal/deepskandpal.github.io#1]
1. Update the README with information about your blog, with due credits(link to the theme you used).
2. Add the actual website link mentioned in the [CNAME](https://github.com/deepskandpal/deepskandpal.github.io/blob/master/CNAME) in the description 

For example.
![image](https://user-images.githubusercontent.com/10382077/56088297-63463c80-5e9b-11e9-93f3-38b25f7ef0c0.png)

**Comment by mbtamuli** [comment]
@deepskandpal You could add this https://utteranc.es/ to your blog. Really easy, 2 minute install. It will give the ability to comment on your blog posts which will help encourage discussions.

**Comment by deepskandpal** [comment]
> @deepskandpal You could add this https://utteranc.es/ to your blog. Really easy, 2 minute install. It will give the ability to comment on your blog posts which will help encourage discussions.

I am able to add the src to the posts/site.html and view the results locally 
![image](https://user-images.githubusercontent.com/10810284/118390584-7fee6900-b64d-11eb-8a49-61711272f910.png)
however when I build the site and push it to the repo I instantly get a mail with build failed, with a generic statement, 

I am not able to debug this for now

**Comment by deepskandpal** [comment]
found it
![image](https://user-images.githubusercontent.com/10810284/118394610-56d8d300-b663-11eb-85dc-439e7cc9a504.png)

maybe there is some problem at Git's end
https://www.githubstatus.com/
